
project_id = "eiueygnrczqrziiviopc"

[functions.sync-bank-data]
verify_jwt = true

[functions.process-recurring-transactions]
verify_jwt = true

[functions.test-pluggy-credentials]
verify_jwt = true

[functions.ai-financial-analysis]
verify_jwt = true

