// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiueygnrczqrziiviopc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpdWV5Z25yY3pxcnppaXZpb3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjczNzEsImV4cCI6MjA2NzMwMzM3MX0.8YX91vJLmOgSSao4CO5RndCRXd5qx6v-2b-70EP5lQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});